### ISSUE TITLE
Header implementation of fclib

### ISSUE THREAD

**Issue by vacary** [FrictionalContactLibrary/fclib#10]
As @dariomangoni suggested, it could be useful to have a header only implementation of the API fclib. Since the source code is really short, It may facilitate its use on various OS and platforms.

What do you think ?

**Comment by dariomangoni** [comment]
The header-only library must be assessed carefully: there is the risk of functions|variables re-definitions and could be troubled since other libraries are linked to it.

**Comment by xhub** [comment]
I think this is already the case: if we request a FCLIB_HEADER_ONLY build, nothing is going to ensure that the library is used if the header is included in another program (like siconos).
