### ISSUE TITLE
Change of SOVERSION caused a CI failure

### ISSUE THREAD

**Issue by radarsat1** [FrictionalContactLibrary/fclib#17]
On launchpad.
Looking into it..

```
Test project /<<PKGBUILDDIR>>/obj-i686-linux-gnu
    Start 1: fctest1
1/2 Test #1: fctest1 ..........................***Failed    0.00 sec
/<<PKGBUILDDIR>>/obj-i686-linux-gnu/fctest1: error while loading shared libraries: libfclib.so.0: cannot open shared object file: No such file or directory

    Start 2: fctest_merit
2/2 Test #2: fctest_merit .....................***Failed    0.00 sec
/<<PKGBUILDDIR>>/obj-i686-linux-gnu/fctest_merit: error while loading shared libraries: libfclib.so.0: cannot open shared object file: No such file or directory


0% tests passed, 2 tests failed out of 2```

**Comment by radarsat1** [comment]
I think it's because the launchpad build disables RPATH (normal for package) but then ctest fails as the executables cannot find the library.  Possibly something that should just be fixed in the build configuration with `LD_LIBRARY_PATH` for example?  @xhub

**Comment by radarsat1** [comment]
[Link to build log](https://launchpadlibrarian.net/360891705/buildlog_ubuntu-trusty-i386.fclib_1.0~alpha-2~201803151847~ubuntu14.04.1_BUILDING.txt.gz)

**Comment by radarsat1** [comment]
Hopefully fixed in b44282b97200fcf33fbb0f8fbb6920303b9d6848

**Comment by xhub** [comment]
Thanks for looking at it.

**Comment by radarsat1** [comment]
Actually just received a new build log report that contained a segfault, which I have seen occasionally but not been able to repeat.  Maybe related to #4?  It does not seem to happen consistently.

**Comment by xhub** [comment]
do we have access to the build log and/or artefacts?

Having a valgrind run could help. Or build it locally with ASAN/MSAN.

**Comment by radarsat1** [comment]
Sure it's [here](https://launchpad.net/~siconos/+archive/ubuntu/fclib-daily/+build/14477239/+files/buildlog_ubuntu-artful-amd64.fclib_1.0~alpha-2~201803201820~ubuntu17.10.1_BUILDING.txt.gz)

Does not contain much info though.  Just,

```

Running tests...
/usr/bin/ctest --force-new-ctest-process -j1
Test project /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu
    Start 1: fctest1
1/2 Test #1: fctest1 ..........................***Exception: SegFault  0.27 sec

    Start 2: fctest_merit
2/2 Test #2: fctest_merit .....................   Passed    0.01 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =   0.28 sec

The following tests FAILED:
	  1 - fctest1 (SEGFAULT)
Errors while running CTest
```

Valgrind is a good idea.
