### ISSUE TITLE
[distribution] Switch to LGPLv3 licence.

### ISSUE THREAD

**Issue by vacary** [FrictionalContactLibrary/fclib#2]
Since the goal of fclib is to be used as a library for reading and writing frictional contact problem, switching to LGPL seems to be natural.

**Comment by xhub** [comment]
Should we move ahead on that one?

**Comment by vacary** [comment]
yes great idea. Gpl3 or Apache 2.0. 
I remember some colleagues that asks for apache licence for outputting new difficult examples in the lib. 
What do you think ?

**Comment by xhub** [comment]
I'm fine with both options. I didn't write much of the code, so I don't think I really have a strong voice. But let's go for Apache 2?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vacary** [comment]
Finally, I switched to Apache 2.0. I put a release tag for that to clearly identify  the change of release.
